version: "2"

services:

  php-base:
    build: base
    command: base
    entrypoint: /security/parse-cve.sh
    volumes:
      - ./cve-reports:/cve-reports
      - ./scripts/parse-cve.sh:/security/parse-cve.sh

  php-5.6-cli:
    build: 5.6/cli
    command: 5.6-cli
    entrypoint: /security/parse-cve.sh
    volumes:
      - ./cve-reports:/cve-reports
      - ./scripts/parse-cve.sh:/security/parse-cve.sh
  php-5.6-fpm:
    build: 5.6/fpm
    command: 5.6-fpm
    entrypoint: /security/parse-cve.sh
    volumes:
      - ./cve-reports:/cve-reports
      - ./scripts/parse-cve.sh:/security/parse-cve.sh

  php-7.0-cli:
    build: 7.0/cli
    command: 7.0-cli
    entrypoint: /security/parse-cve.sh
    volumes:
      - ./cve-reports:/cve-reports
      - ./scripts/parse-cve.sh:/security/parse-cve.sh
  php-7.0-fpm:
    build: 7.0/fpm
    command: 7.0-fpm
    entrypoint: /security/parse-cve.sh
    volumes:
      - ./cve-reports:/cve-reports
      - ./scripts/parse-cve.sh:/security/parse-cve.sh

  php-7.1-cli:
    build: 7.1/cli
    command: 7.1-cli
    entrypoint: /security/parse-cve.sh
    volumes:
      - ./cve-reports:/cve-reports
      - ./scripts/parse-cve.sh:/security/parse-cve.sh
  php-7.1-fpm:
    build: 7.1/fpm
    command: 7.1-fpm
    entrypoint: /security/parse-cve.sh
    volumes:
      - ./cve-reports:/cve-reports
      - ./scripts/parse-cve.sh:/security/parse-cve.sh

  php-7.2-cli:
    build: 7.2/cli
    command: 7.2-cli
    entrypoint: /security/parse-cve.sh
    volumes:
      - ./cve-reports:/cve-reports
      - ./scripts/parse-cve.sh:/security/parse-cve.sh
  php-7.2-fpm:
    build: 7.2/fpm
    command: 7.2-fpm
    entrypoint: /security/parse-cve.sh
    volumes:
      - ./cve-reports:/cve-reports
      - ./scripts/parse-cve.sh:/security/parse-cve.sh

  php-7.3-cli:
    build: 7.3/cli
    command: 7.3-cli
    entrypoint: /security/parse-cve.sh
    volumes:
      - ./cve-reports:/cve-reports
      - ./scripts/parse-cve.sh:/security/parse-cve.sh
  php-7.3-fpm:
    build: 7.3/fpm
    command: 7.3-fpm
    entrypoint: /security/parse-cve.sh
    volumes:
      - ./cve-reports:/cve-reports
      - ./scripts/parse-cve.sh:/security/parse-cve.sh

  php-7.4-cli:
    build: 7.4/cli
    command: 7.4-cli
    entrypoint: /security/parse-cve.sh
    volumes:
      - ./cve-reports:/cve-reports
      - ./scripts/parse-cve.sh:/security/parse-cve.sh
  php-7.4-fpm:
    build: 7.4/fpm
    command: 7.4-fpm
    entrypoint: /security/parse-cve.sh
    volumes:
      - ./cve-reports:/cve-reports
      - ./scripts/parse-cve.sh:/security/parse-cve.sh

  php-8.0-cli:
    build: 8.0/cli
    command: 8.0-cli
    entrypoint: /security/parse-cve.sh
    volumes:
      - ./cve-reports:/cve-reports
      - ./scripts/parse-cve.sh:/security/parse-cve.sh
  php-8.0-fpm:
    build: 8.0/fpm
    command: 8.0-fpm
    entrypoint: /security/parse-cve.sh
    volumes:
      - ./cve-reports:/cve-reports
      - ./scripts/parse-cve.sh:/security/parse-cve.sh

  php-8.1-cli:
    build: 8.1/cli
    command: 8.1-cli
    entrypoint: /security/parse-cve.sh
    volumes:
      - ./cve-reports:/cve-reports
      - ./scripts/parse-cve.sh:/security/parse-cve.sh
  php-8.1-fpm:
    build: 8.1/fpm
    command: 8.1-fpm
    entrypoint: /security/parse-cve.sh
    volumes:
      - ./cve-reports:/cve-reports
      - ./scripts/parse-cve.sh:/security/parse-cve.sh

  php-8.2-cli:
    build: 8.2/cli
    command: 8.2-cli
    entrypoint: /security/parse-cve.sh
    volumes:
      - ./cve-reports:/cve-reports
      - ./scripts/parse-cve.sh:/security/parse-cve.sh
  php-8.2-fpm:
    build: 8.2/fpm
    command: 8.2-fpm
    entrypoint: /security/parse-cve.sh
    volumes:
      - ./cve-reports:/cve-reports
      - ./scripts/parse-cve.sh:/security/parse-cve.sh